/**
 * Generate `src/generated/types.gen.ts` from the pinned vendored Firecracker
 * swagger spec, plus `spec/surface-diff.json` describing what the pinned
 * spec adds over the previous supported minor.
 *
 * Deterministic: output depends only on the vendored specs and the locked
 * generator dependencies, so CI can verify `regen == committed`.
 *
 * Usage: deno task codegen
 *
 * @module
 */

import { parse } from "@std/yaml";
import openapiTS, { astToString } from "openapi-typescript";
import s2o from "swagger2openapi";

interface Versions {
  pinned: string;
  previous: string;
}

interface SwaggerDoc {
  paths?: Record<string, Record<string, unknown>>;
  definitions?: Record<string, { properties?: Record<string, unknown> }>;
}

const HTTP_METHODS = ["get", "put", "patch", "post", "delete"];

async function loadSpec(
  tag: string,
): Promise<{ raw: string; doc: SwaggerDoc }> {
  const raw = await Deno.readTextFile(`spec/firecracker-${tag}.yaml`);
  return { raw, doc: parse(raw) as SwaggerDoc };
}

function operations(doc: SwaggerDoc): string[] {
  const ops: string[] = [];
  for (const [path, item] of Object.entries(doc.paths ?? {})) {
    for (const method of Object.keys(item)) {
      if (HTTP_METHODS.includes(method)) {
        ops.push(`${method.toUpperCase()} ${path}`);
      }
    }
  }
  return ops.sort();
}

function schemaProperties(doc: SwaggerDoc): string[] {
  const props: string[] = [];
  for (const [name, def] of Object.entries(doc.definitions ?? {})) {
    props.push(name);
    for (const prop of Object.keys(def.properties ?? {})) {
      props.push(`${name}.${prop}`);
    }
  }
  return props.sort();
}

async function sha256Hex(text: string): Promise<string> {
  const digest = await crypto.subtle.digest(
    "SHA-256",
    new TextEncoder().encode(text),
  );
  return Array.from(new Uint8Array(digest))
    .map((b) => b.toString(16).padStart(2, "0"))
    .join("");
}

export async function generate(): Promise<{
  typesSource: string;
  meta: Record<string, string>;
  surfaceDiff: Record<string, string[]>;
}> {
  const versions: Versions = JSON.parse(
    await Deno.readTextFile("spec/versions.json"),
  );
  const pinned = await loadSpec(versions.pinned);
  const previous = await loadSpec(versions.previous);

  // Swagger 2.0 → OpenAPI 3.0, then → TypeScript.
  const converted = await s2o.convertObj(pinned.doc, {
    patch: true,
    warnOnly: true,
  });
  const ast = await openapiTS(converted.openapi, {
    alphabetize: true,
    // A schema `default` means Firecracker fills the value in — callers may
    // omit it. Without this, defaulted fields are generated as required.
    defaultNonNullable: false,
  });
  const body = astToString(ast);

  const meta = {
    pinned: versions.pinned,
    previous: versions.previous,
    specSha256: await sha256Hex(pinned.raw),
    previousSpecSha256: await sha256Hex(previous.raw),
  };

  const header = `// AUTOGENERATED FILE — DO NOT EDIT.
//
// Generated by tools/codegen.ts from spec/firecracker-${versions.pinned}.yaml
// (sha256 ${meta.specSha256}).
// Regenerate with: deno task codegen
//
// deno-lint-ignore-file
// deno-fmt-ignore-file

`;

  const prevOps = new Set(operations(previous.doc));
  const prevProps = new Set(schemaProperties(previous.doc));
  const surfaceDiff = {
    operationsAddedSincePrevious: operations(pinned.doc).filter((op) =>
      !prevOps.has(op)
    ),
    schemaSurfaceAddedSincePrevious: schemaProperties(pinned.doc).filter((p) =>
      !prevProps.has(p)
    ),
    operationsRemovedSincePrevious: [...prevOps].filter((op) =>
      !operations(pinned.doc).includes(op)
    ).sort(),
  };

  return { typesSource: header + body, meta, surfaceDiff };
}

if (import.meta.main) {
  const { typesSource, meta, surfaceDiff } = await generate();
  await Deno.mkdir("src/generated", { recursive: true });
  await Deno.writeTextFile("src/generated/types.gen.ts", typesSource);
  await Deno.writeTextFile(
    "src/generated/codegen-meta.json",
    JSON.stringify(meta, null, 2) + "\n",
  );
  await Deno.writeTextFile(
    "spec/surface-diff.json",
    JSON.stringify(surfaceDiff, null, 2) + "\n",
  );
  console.log(
    `wrote src/generated/types.gen.ts (${typesSource.length} bytes), ` +
      `codegen-meta.json, spec/surface-diff.json`,
  );
  console.log(
    `surface added since ${meta.previous}: ` +
      `${surfaceDiff.operationsAddedSincePrevious.length} operation(s), ` +
      `${surfaceDiff.schemaSurfaceAddedSincePrevious.length} schema member(s)`,
  );
}
